import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import type { AgentModel } from "../types/index.js";
import type { ResolvedConfig } from "./config.js";

let cachedBin: string | null = null;

export function claudeBin(): string {
  if (cachedBin) return cachedBin;
  cachedBin = resolveClaudeBin();
  return cachedBin;
}

function resolveClaudeBin(): string {
  if (process.env.CLAUDE_BIN && existsSync(process.env.CLAUDE_BIN)) return process.env.CLAUDE_BIN;

  const local = join(process.cwd(), "node_modules", ".bin", "claude");
  if (existsSync(local)) return local;

  const home = homedir();
  const candidates = [
    join(home, ".claude", "local", "claude"),
    "/opt/homebrew/bin/claude",
    "/usr/local/bin/claude",
    join(home, ".local", "bin", "claude"),
    join(home, ".npm-global", "bin", "claude"),
  ];
  for (const c of candidates) if (existsSync(c)) return c;

  try {
    const shell = process.env.SHELL || "/bin/zsh";
    const found = execFileSync(shell, ["-lic", "command -v claude"], {
      encoding: "utf8",
      timeout: 4000,
    })
      .split("\n")
      .map((l) => l.trim())
      .filter(Boolean)
      .pop();
    if (found) return found;
  } catch {
    /* fall through */
  }

  return "claude";
}

let cachedPath: string | null = null;

function loginShellPath(): string {
  if (cachedPath) return cachedPath;
  const home = homedir();
  const parts = new Set<string>((process.env.PATH || "").split(":").filter(Boolean));
  try {
    const shell = process.env.SHELL || "/bin/zsh";
    const out = execFileSync(shell, ["-lic", "echo $PATH"], { encoding: "utf8", timeout: 4000 })
      .split("\n")
      .map((s) => s.trim())
      .filter(Boolean)
      .pop();
    for (const p of (out || "").split(":")) if (p) parts.add(p);
  } catch {
    /* ignore */
  }
  for (const p of ["/opt/homebrew/bin", "/usr/local/bin", join(home, ".claude", "local"), join(home, ".local", "bin")]) {
    parts.add(p);
  }
  cachedPath = Array.from(parts).join(":");
  return cachedPath;
}

export function agentEnv(extraEnv?: Record<string, string>): NodeJS.ProcessEnv {
  return { ...process.env, PATH: loginShellPath(), ...extraEnv };
}

/**
 * Materialize the agent settings file at <cwd>/.design-agent/agent-settings.json
 * with an absolute path to this package's shipped secret-guard hook.
 * Cached per cwd.
 */
const materializedPaths = new Map<string, string>();

export function agentSettingsPath(cfg: ResolvedConfig): string {
  const cached = materializedPaths.get(cfg.cwd);
  if (cached) return cached;

  // Resolve the absolute path to assets/secret-guard.mjs relative to this file.
  // At runtime (in node_modules): …/@payglocal_ui/lumen/dist/server/claudeCli.js
  // assets/secret-guard.mjs is at: …/@payglocal_ui/lumen/assets/secret-guard.mjs
  const hookPath = new URL("../../assets/secret-guard.mjs", import.meta.url).pathname;

  const settingsDir = join(cfg.cwd, ".design-agent");
  const settingsPath = join(settingsDir, "agent-settings.json");

  if (!existsSync(settingsDir)) mkdirSync(settingsDir, { recursive: true });

  // Serialize extra secret patterns as JSON for the hook subprocess.
  const patternDefs = cfg.secretPatterns.map((re) => ({ source: re.source, flags: re.flags }));

  const settings = {
    $comment: "Auto-generated by @payglocal_ui/lumen — do not edit",
    hooks: {
      PreToolUse: [
        {
          matcher: "Read|Edit|Write|Bash",
          hooks: [
            {
              type: "command",
              command: `node ${JSON.stringify(hookPath)}`,
            },
          ],
        },
      ],
    },
    env: {
      LUMEN_SECRET_PATTERNS: JSON.stringify(patternDefs),
    },
  };

  writeFileSync(settingsPath, JSON.stringify(settings, null, 2), "utf8");
  materializedPaths.set(cfg.cwd, settingsPath);
  return settingsPath;
}

export function buildChatArgs(
  opts: {
    prompt: string;
    model: AgentModel;
    systemAppend: string;
    sessionId?: string;
    imageBase64?: string;
    imageMimeType?: string;
  },
  cfg: ResolvedConfig,
): { args: string[]; stdinData?: string } {
  const hasImage = !!(opts.imageBase64 && opts.imageMimeType);

  const args = [
    ...(hasImage ? ["--print"] : ["-p", opts.prompt]),
    "--output-format",
    "stream-json",
    "--include-partial-messages",
    "--verbose",
    "--model",
    opts.model,
    "--permission-mode",
    "dontAsk",
    "--allowedTools",
    cfg.allowedTools.join(" "),
    "--append-system-prompt",
    opts.systemAppend,
    "--settings",
    agentSettingsPath(cfg),
  ];
  if (hasImage) args.push("--input-format", "stream-json");
  for (const dir of cfg.referenceDirs.filter(existsSync)) args.push("--add-dir", dir);
  if (opts.sessionId) args.push("--resume", opts.sessionId);

  let stdinData: string | undefined;
  if (hasImage) {
    const content: unknown[] = [
      { type: "image", source: { type: "base64", media_type: opts.imageMimeType, data: opts.imageBase64 } },
    ];
    if (opts.prompt) content.push({ type: "text", text: opts.prompt });
    stdinData = JSON.stringify({ type: "user", message: { role: "user", content } }) + "\n";
  }

  return { args, stdinData };
}
